targets:
  $default:
    builders:
      source_gen:combining_builder:
        options:
          build_extensions:
            '^lib/data/{{}}.dart': 'lib/generated/{{}}.g.dart'
      json_serializable:
        options:
          explicit_to_json: true