name: billsplit_flutter
description: A new Flutter project
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+21

environment:
  sdk: '>=2.19.2 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  cupertino_icons: ^1.0.2
  http: ^0.13.5
  json_annotation: ^4.8.0
  firebase_auth: ^4.4.0
  firebase_core: ^2.9.0
  drift: ^2.6.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  path: ^1.8.2
  storage_inspector: ^0.3.0
  rxdart: ^0.27.7
  collection:
  get_it: ^7.2.0
  intl: ^0.17.0
  email_validator:
  cached_network_image: ^3.2.3
  firebase_storage: ^11.1.1
  image_picker: ^0.8.7+4
  cupertino_will_pop_scope: ^1.2.1
  firebase_messaging: ^14.5.0
  flutter_local_notifications: ^14.0.0+1
  shared_preferences: ^2.1.0
  eraser: ^2.0.1
  firebase_crashlytics: ^3.3.1

dev_dependencies:
  json_serializable: ^6.6.1
  build_runner: ^2.3.3
  drift_dev: ^2.6.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
