name: billsplit_flutter
description: A new expense sharing experience
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.3+76

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # firebase
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  firebase_storage: ^13.0.1
  firebase_messaging: ^16.0.1
  firebase_crashlytics: ^5.0.1

  flutter_bloc: ^9.1.1
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1
  drift: ^2.6.0
  sqlite3_flutter_libs: ^0.5.23
  path_provider: ^2.0.0
  path: ^1.8.2
  storage_inspector: ^0.4.0
  rxdart: ^0.28.0
  collection:
  get_it: ^8.0.3
  intl: ^0.20.2
  email_validator:
  cached_network_image: ^3.2.3
  image_picker: ^1.0.4
  cupertino_will_pop_scope: ^1.2.1
  flutter_local_notifications: ^19.4.1
  shared_preferences: ^2.1.0
  eraser: ^3.0.0
  camera: ^0.11.1 
  flutter_animate: ^4.1.1+1
  package_info_plus: ^8.0.0
  uuid: ^4.1.0
  json_pretty: ^1.0.4
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^7.0.1
  country_code_picker: ^3.0.0
  image_cropper: ^9.1.0
  google_mlkit_text_recognition: ^0.15.0
  phone_numbers_parser: ^9.0.11

dev_dependencies:
  build_runner: ^2.3.3
  drift_dev: ^2.6.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/splitsby_logo.jpg
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
          style: normal
        - asset: fonts/Montserrat-Light.ttf
          weight: 200
        - asset: fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: fonts/Montserrat-Italic.ttf
          style: italic