steps:
  - name: Set up Flutter
    uses: subosito/flutter-action@v2
    with:
      channel: stable
      flutter-version: 3.32.5

  - name: Clone repository
    uses: actions/checkout@v5
    with:
      fetch-depth: 0