// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuk0HYl6fJ3XLU1zZzce6bQyQIpzJD64w',
    appId: '1:469876198103:android:479058527187a4c96dfe92',
    messagingSenderId: '469876198103',
    projectId: 'billsplittapp',
    storageBucket: 'billsplittapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCABQuP7HOq_XnhTLHPTKFFU4YyxCqDz4o',
    appId: '1:469876198103:ios:7a9ad3db28d3524a6dfe92',
    messagingSenderId: '469876198103',
    projectId: 'billsplittapp',
    storageBucket: 'billsplittapp.appspot.com',
    androidClientId:
        '469876198103-37j14ctjitf2gp7rvana3stcpt4dt5l3.apps.googleusercontent.com',
    iosClientId:
        '469876198103-db9i89patfeg6jkbu128dhejtjkk5v8u.apps.googleusercontent.com',
    iosBundleId: 'com.mikkelthygesen.splitsby',
  );
}
