import 'package:billsplit_flutter/domain/models/person.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

class AutoGeneratedProfilePicture extends StatelessWidget {
  final Person person;
  final double size;

  const AutoGeneratedProfilePicture(
      {super.key, required this.person, required this.size});

  @override
  Widget build(BuildContext context) {
    final userName = person.displayName;
    String displayName;
    if (userName.trim().contains(" ")) {
      final split = userName.split(" ").where((element) => element.isNotEmpty);
      final initials = split
          .map((e) => e[0])
          .fold("", (previousValue, element) => "$previousValue$element");
      displayName = initials.toUpperCase();
      if (displayName.length > 1) {
        displayName = displayName.substring(0, 2);
      }
    } else {
      displayName = userName[0].toUpperCase();
    }
    final color = Color(person.uid.hashCode).withAlpha(100);
    return ClipOval(
      child: Container(
        alignment: Alignment.center,
        height: size,
        width: size,
        color: color,
        child: Text(
          displayName,
          maxLines: 1,
          style: TextStyle(
            fontSize: (size / 2.5),
            color: Theme.of(context).colorScheme.brightness == Brightness.light
                ? Colors.black
                : Colors.white,
          ),
        ),
      ),
    );
  }
}
