import 'package:billsplit_flutter/domain/models/person.dart';
import 'package:billsplit_flutter/presentation/common/auto_generated_pfp.dart';
import 'package:billsplit_flutter/presentation/common/circular_frame.dart';
import 'package:cached_network_image/cached_network_image.dart';
import 'package:flutter/material.dart';

class ProfilePictureView extends StatelessWidget {
  final Person person;
  final double size;
  final bool showBorder;

  const ProfilePictureView(
      {Key? key,
      required this.person,
      this.size = 40.0,
      this.showBorder = false})
      : super(key: key);

  @override
  Widget build(BuildContext context) {
    if (person.pfpUrlState.isEmpty) {
      return CircularFrame(
          show: showBorder,
          child: AutoGeneratedProfilePicture(person: person, size: size));
    }
    return CircularFrame(
      show: showBorder,
      child: ClipOval(
        child: CachedNetworkImage(
            imageUrl: person.pfpUrlState,
            width: size,
            height: size,
            fit: BoxFit.cover),
      ),
    );
  }
}
