import 'package:billsplit_flutter/domain/models/person.dart';
import 'package:billsplit_flutter/presentation/common/auto_generated_pfp.dart';
import 'package:billsplit_flutter/presentation/common/circular_frame.dart';
import 'package:billsplit_flutter/presentation/features/inspect_profile/inspect_profile_page.dart';
import 'package:cached_network_image/cached_network_image.dart';
import 'package:flutter/material.dart';

class ProfilePictureView extends StatelessWidget {
  final Person person;
  final double size;
  final bool showBorder;
  final bool canInspect;

  const ProfilePictureView({
    super.key,
    required this.person,
    this.size = 40.0,
    this.canInspect = false,
    this.showBorder = false,
  });

  Function? get onTap => canInspect ? () {} : null;

  @override
  Widget build(BuildContext context) {
    final onTap = canInspect
        ? () {
            Navigator.of(context).push(InspectProfilePage.getRoute(person));
          }
        : null;

    return InkWell(
      onTap: onTap,
      child: Builder(
        builder: (context) {
          final pfpUrl = person.pfpUrlState.value;
          if (pfpUrl.isEmpty) {
            return CircularFrame(
                show: showBorder,
                child: AutoGeneratedProfilePicture(person: person, size: size));
          }
          return CircularFrame(
            show: showBorder,
            child: ClipOval(
              child: CachedNetworkImage(
                  imageUrl: pfpUrl,
                  width: size,
                  height: size,
                  fit: BoxFit.cover),
            ),
          );
        },
      ),
    );
  }
}
