name: Build-iOS

on:
  push:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: macos-26
    steps:
      - name: Clone repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0 # we need the git history for the build number

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.38.9

      - uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: xcode version
        run: |
          sudo xcode-select -s /Applications/Xcode_26.2.app
          /usr/bin/xcodebuild -version

      - name: install flutterfire
        run: |
          npm install -g firebase-tools
          dart pub global activate flutterfire_cli

      - name: Install the Apple certificate and provisioning profile
        env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.CERTIFICATE_P12_31_01_2027 }}
          APN_CERTIFICATE_B64: ${{ secrets.APN_CERTIFICATE }}
          P12_PASSWORD: ${{ secrets.P12_PASSWORD_2 }}
          BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.DEV_PROD_MOBILEPROVISION }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        run: |
          # create variables
          CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
          PP_PATH=$RUNNER_TEMP/build_pp.mobileprovision
          APN_CERT_PATH=$RUNNER_TEMP/apn_cert.p12
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db
          
          # import certificate and provisioning profile from secrets
          echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode -o $CERTIFICATE_PATH
          echo -n "$BUILD_PROVISION_PROFILE_BASE64" | base64 --decode -o $PP_PATH
          echo -n "$APN_CERTIFICATE_B64" | base64 --decode -o $APN_CERT_PATH
          
          # create temporary keychain
          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          
          # import certificate to keychain
          security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security import $APN_CERT_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security set-key-partition-list -S apple-tool:,apple: -k "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH
          
          # apply provisioning profile
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles

      - name: Update xcode build number
        run: bash scripts/ci-cd/ios-set-build-number.sh

      - name: flutter build ipa
        run: flutter build ipa --release --no-codesign

      - name: Archive
        env:
          CONFIGURATION: Release
          WORKSPACE: ios/Runner.xcworkspace
          SCHEME: Runner
          CERTIFICATE_ID: "Apple Distribution: Mikkel Thygesen (88JMYVVGNH)"
          PROFILE_ID: abe11ac0-949d-40d8-bb80-406cd39ad9df
          TEAM_ID: 88JMYVVGNH
          ARCHIVE_PATH: ios/build/Runner.xcarchive
        run: >-
          xcodebuild build -sdk iphoneos  
          -configuration $CONFIGURATION 
          -workspace $WORKSPACE  
          -archivePath $ARCHIVE_PATH  
          -scheme $SCHEME
          CODE_SIGN_STYLE=Manual  
          CDE_SIGN_IDENTITY="$CERTIFICATE_ID"  
          PROVISIONING_PROFILE=$PROFILE_ID  
          CODE_SIGNING_REQUIRED=Yes  
          CODE_SIGNING_ALLOWED=No  
          PROVISIONING_PROFILE_SPECIFIER=

      - name: export
        env:
          ARCHIVE_PATH: build/ios/archive/Runner.xcarchive
          EXPORT_OPTIONS_PATH: ios/ExportOptions.plist
          EXPORT_PATH: output
        run: >-
          xcodebuild -exportArchive 
          -archivePath $ARCHIVE_PATH 
          -exportPath $EXPORT_PATH 
          -exportOptionsPlist $EXPORT_OPTIONS_PATH

      - name: Validate & upload
        env:
          API_KEY: ${{ secrets.APP_STORE_API_KEY }}
          ISSUER_ID: ${{ secrets.APP_STORE_ISSUER_ID }}
          APP_STORE_KEY_ID: ${{ secrets.APP_STORE_KEY_ID }}
          WORKSPACE_PATH: ${{ github.workspace }}
          IPA_PATH: output/splitsby.ipa
        run: |
          mkdir ~/.private_keys
          API_KEY_FILE_NAME=AuthKey_$APP_STORE_KEY_ID.p8
          API_KEY_PATH=~/.private_keys/$API_KEY_FILE_NAME
          echo -n "$API_KEY" | base64 --decode -o $API_KEY_PATH
          
          xcrun altool --validate-app -f $IPA_PATH -t ios --apiKey $APP_STORE_KEY_ID --apiIssuer $ISSUER_ID
          xcrun altool --upload-app -f $IPA_PATH -t ios --apiKey $APP_STORE_KEY_ID --apiIssuer $ISSUER_ID